### ISSUE TITLE
Request for comment on paper

### ISSUE THREAD

**Issue by r4space** [polar-computing/Papers#1]
Hi all, @andypbarrett @treerink @aborowicz @akpetty @bentocg @kacasey @phil-mcdowall 

If anyone's interested and would like to comment, we wrote up the last hack as a paper here, suggesting hackathons - in combination with domain specific training - could offer a useful model of equipping domain scientists to use HPDC resources.

We learnt a lot from all of you and this process - and will be modding the way we do things accordingly for the next round - so any more input you have that you would like to feed back will definitely be taken onboard and hopefully used to improve things.

So feel free to push changes to this paper, and/or leave any comments you want here.

**Comment by akpetty** [comment]
Good job! I find it a lot easier to provide comments etc on word instead of GitHub (maybe this helps prove some of your points!), so see attached  [HackathonPaper.docx](https://github.com/polar-computing/Papers/files/846250/HackathonPaper.docx)

**Comment by r4space** [comment]
@akpetty Thanks for the input!
Have taken on most of the editing changes and replied to content comments - see uploaded doc in repo.

Could you elaborate more on these two tho:

1. What you meant about being confused by: "Priority in training scientists is unavoidably given to the domain science itself. Yet, the rate of technological change means easy-to-use tools of abstraction and formal undergraduate and graduate HPDC training generally lags far behind. "

We mean training to be a domain expert is obviously dominated by the domain content itself with scare space for tech skills input, and the rate of change in tech means the tech community can't abstract the tech (make tech easy to use) fast enough for domain scientists to NOT need formal training input.

2. you comment"seems a bit too far, as it might be the right model, but needs more support to aid its success (my view!)?" 

On our statement:
"The experience taught us that the hackathon model is an effective **but imperfect and incomplete** means of bridging the divide between HPDC and non-programmer domain specialist users (in this case in the polar sciences)."

Have we not been explicit enough that we recognise it is incomplete and needs support via pre and post event input? Would this be better:

"The experience taught us that the hackathon model is an effective **but imperfect and incomplete** means of bridging the divide between HPDC and non-programmer domain specialist users (in this case in the polar sciences).  Specifically, as is elaborated on later, dedicated training input is still required, but we see the hackathon model as a valuable means of facilitating a path from taught theory to an accessible and applicable tool of relevance to specific users work."

**Comment by r4space** [comment]
@allenpope @hlynch I took on the comments I could and made changes in latest push. I think these comments from Alek though would be best addressed by you two as domain specialists.  Page references are to his doc - I've added it with my comments to the repo so just pull again.  Confusing using a word doc and latex so to be clear I'm making all changes in the final latex doc and am just using the word doc as reference/comment space.

1. Change following reference to IPCC report: pg1
  [1] F. Nelson, K. Kobak, and B. Sinclair, Polar Regions (Arctic and
Antarctic). Cambridge University Press, 2007, no. January. 

2. His comment on our surmising researchers might want to do this training while in the field:  "Hmm, I'm not hugely convinced people will do this when they're away! Would soften this in my view and just say can do this anywhere potentially."  pg4, comment 4

3. He comments that not all polar scientists spend extensive time in the field, and that particularly the next generation is more computationally focused.  pg5 last comment

**Comment by akpetty** [comment]
1. Was confused by "easy-to-use tools of abstraction" but it seems you mean training in more HPDC or even just computational methods. In general I don't think scientists do much training on anything!

2. Yeah I think my concern was that you were extrapolating from a small sample, but agree with your points so maybe ignore my concern!

p.s. I don'k that citation matters much. Think the other points are still valid in my mind though.

Thanks!

Alek

**Comment by andypbarrett** [comment]
Jane

I've attached the paper with comments.

Overall, the paper looks good.  I like the idea of combining a hackathon
with some kind of X-Carpentry short-course.

Andy
