### ISSUE TITLE
ALT-HPDC

### ISSUE THREAD

**Issue by shantenujha** [polar-computing/Papers#4]
Does this have an unintended resemblance to the "ALT-Right" ((https://en.wikipedia.org/wiki/Alt-right)) movement supporting Trump? If so, should be fix before we become

**Comment by r4space** [comment]
Is kind of uncomfortably similar.  Also Alek comments: "hmm, this seems a bit of a stretch.."
"ALT-HPDC training is focused on communicating what's Appropriate & Available (A), communicating clearly the Lingo (L) of HPDC, and is Tailored (T) to only cover those aspects of HPDC that are essential for a domain's users. " 

Instead how about just:
DOMAIN-HPDC
or
DICIPLINE-HPDC

or if we really want an Achronym, some brain storming in public ;)

TALES-HPDC or TAILS-HPDC
Tailored, Available, Lingo corrected, Effective, Systematic   
Tailored, Available, Interpreted Lingo, Systematic

**Comment by r4space** [comment]
Or actually prefer @akpetty's suggestion

lite-HPDC

**Comment by shantenujha** [comment]
ALITE (appropriate & Available (A)), communicating clearly the Lingo (LI) of HPDC, and is Tailored (T)  and Extensible (E) (=modular) to only cover those aspects of HPDC that are essential for a domain's users. "

ALITE HPDC 

OK?

**Comment by shantenujha** [comment]
Also, suggestions on how to compare and contrast ALITE (?) HPDC  with more established taxonomys like Blooms? 

If so, where?

**Comment by shantenujha** [comment]
* Maps to lower two levels of Blooms

**Comment by shantenujha** [comment]
moving to #7 (https://github.com/polar-computing/Papers/issues/7)
