### ISSUE TITLE
Compute hours used

### ISSUE THREAD

**Issue by r4space** [polar-computing/Papers#5]
Add how many hours we used

**Comment by shantenujha** [comment]
Placed in outcome. OK? Please review and feel to edit.

**Comment by r4space** [comment]
Looks good, needs a legend?  What's blue vs red.  And we should try integrate - might be short on space

**Comment by shantenujha** [comment]
As this was a screen grab, wasn't able to provide a legend. 

Mentioned in caption: Blue is the number of jobs, red is the number of core-hours.

Sorry, not sure what "Integrate" means?

**Comment by shantenujha** [comment]
aha.. git pushed. does this resolve the problem?


> "Integrate" was  - I see the pdf with the graph but there's nothing in the latex pulling it in.
> Maybe just missed including latex changes in commit?

**Comment by r4space** [comment]
Yip :)

++++++++++++++++
Jane Wyngaard, PhD

Data Science Technologist
Centre for Research Computing
University of Notre Dame
